// Generated by https://quicktype.io

export interface PlacesResponse {
    place_id:     string;
    licence:      string;
    osm_type:     OsmType;
    osm_id:       string;
    boundingbox:  string[];
    lat:          string;
    lon:          string;
    display_name: string;
    class:        Class;
    type:         string;
    importance:   number;
    icon?:        string;
}

export enum Class {
    Amenity = "amenity",
    Shop = "shop",
}

export enum OsmType {
    Node = "node",
    Way = "way",
}
